### ISSUE TITLE
Using heapdump with io.js

### ISSUE THREAD

**Issue by zeusdeux** [bnoordhuis/node-heapdump#48]
Right now, I get the following when I try to start up my app.

```bash
module.js:345
    throw err;
          ^
Error: Cannot find module '../build/Debug/addon'
    at Function.Module._resolveFilename (module.js:343:15)
    at Function.Module._load (module.js:285:25)
    at Module.require (module.js:372:17)
    at require (module.js:391:17)
    at Object.<anonymous> (/Users/zeusdeux/experiments/schema-check/node_modules/heapdump/lib/main.js:18:15)
    at Module._compile (module.js:467:26)
    at Object.Module._extensions..js (module.js:485:10)
    at Module.load (module.js:362:32)
    at Function.Module._load (module.js:317:12)
    at Module.require (module.js:372:17)
```

I have tried rebuilding it using `node-gyp configure install` but that didn't help either.

It isn't able to load up `addon.node` which is present in the `../build/Release/` and hence tries to load from `Debug`.

Any idea why it refuses to load the `addon.node` file from `Release` folder?

**Comment by bnoordhuis** [comment]
@zeusdeux Thanks for the bug report.  It should be fixed now in v0.3.4.

**Comment by zeusdeux** [comment]
No problem. 
Let me test that in a few hours.

**Comment by ssmlee04** [comment]
I am still having this problem. My node is 0.12.0 and heapdump is 0.3.5.  Wondering if this is solved yet?  Thanks.

**Comment by bnoordhuis** [comment]
@ssmlee04 It should be.  If installing doesn't work for you, can you file a new issue and include the full output of npm-debug.log and/or `node-gyp rebuild`?

**Comment by francisdb** [comment]
We have this inside a docker image, but probably related to doing `npm update` outside of the docker image build?

**Comment by bnoordhuis** [comment]
@francisdb That sounds a lot like #55, which indeed was about building heapdump outside the docker image.

**Comment by francisdb** [comment]
@bnoordhuis thanks for the pointer!

**Comment by rainabba** [comment]
Ironic. I had heapdump implemented inside Hapi Poop and it was preventing my app from running on Node 4.0.0. SO the tool intended to help me understand and handle crashes was crashing my app :)

Poop wasn't to blame to be clear, but I'm thinking heapdump isn't ready for Node 4.0 yet?

**Comment by bnoordhuis** [comment]
@rainabba It works with node v4 just fine.  If you experience crashes, please file a bug report and include a (gdb) stack trace.
