### ISSUE TITLE
Incomplete heap dump?

### ISSUE THREAD

**Issue by jspavlick** [bnoordhuis/node-heapdump#62]
I'm having trouble figuring out a memory leak. Both New Relic and Heroku are reporting that I am hitting the Heroku memory quota of 512MB.

Looks like a leak alright...
![screenshot 2015-08-25 10 00 02](https://cloud.githubusercontent.com/assets/5431318/9473543/30e98870-4b10-11e5-84e8-7455c7cac388.png)

However, my post-boot (i.e. when no leaks should have occurred) and pre-reboot (i.e. in full leak-mode) dumps are...less than helpful...

![screenshot 2015-08-25 10 01 44](https://cloud.githubusercontent.com/assets/5431318/9473568/521611b2-4b10-11e5-80a4-380a8eef417a.png)

According to heap dump the heap has grown....7MB? I don't think so....?

Am I doing something wrong? I'm running Node 0.12.7 on Heroku.

**Comment by jspavlick** [comment]
duplicate of https://github.com/bnoordhuis/node-heapdump/issues/50

**Comment by ChALkeR** [comment]
If you use 0.12 and perform https requests (for example), you might be hit by something like https://github.com/nodejs/node/issues/1522 (fixed in 1.8.2) — that's outside of the heap and is not visible in heapUsed and/or heap snapshots.

**Comment by jspavlick** [comment]
Gah. We do perform https requests from the server. This still happens in Node 0.12.7? I'd rather not migrate to iojs. Is there a way to ```setInterval(global.force_gc, 60 * 1000);``` ?

**Comment by jspavlick** [comment]
Wow. That worked amazingly. 

<img width="817" alt="screenshot 2015-09-03 20 23 03" src="https://cloud.githubusercontent.com/assets/5431318/9675978/9ceee324-5279-11e5-93c6-17e16c0b9bf9.png">

**Comment by BernhardBezdek** [comment]
@jspavlick Did there came any negative things up since you're running  your application with ``--expose-gc`` param (like less rpm, more cpu load or similar thing)?
I'm currently working on memory analysis in my application and got my cpu on a constantly lower level when I'm using expose-gc. I've understand so far that gc completely stops the application until it's running but didn't run into measurable problems yet.

**Comment by jspavlick** [comment]
@BernhardBezdek not sure if I can answer your question very well. I haven't done any extensive profiling, but everything *seems* to be fine. (Yes I know, I am a bad person haha)

I have done some times.
```
var start = new Date();
global.gc();
var stop = new Date();
console.log('GC took', stop - start, 'ms');
```

And sometimes the GC takes really long. Like, over 1000ms. If the process is in the middle of servicing an HTTP request, that's going to kill the response time, since the GC locks the process until it's finished, as you said. Now, I'm not sure if the "system-invoked" GC also takes over 1000ms. If so, well, no difference. If not...then I am sure I am increasing my 99 percentile response time.

The alternative, for me at least, was to manually reboot the process every ~8 hours. If I would forget, it would hit Heroku out of memory errors and requests would start timing out left and right. So for me at least, this is the lesser of the two evils.

**Comment by BernhardBezdek** [comment]
@jspavlick Thanks for your response. I'm actually using garbage collector too and have a better memory allocation but an comment on stackoverflow was against the gc:

**Running with --expose-gc and calling gc() periodically is bad practice. V8 collects garbage as needed via incremental marking and lazy sweeping. A suitable way to handle the behavior above **


Now after one more day analyzing and optimizing I found two main issues...
there were two cases where DB results were loaded into ram instead of sending a stream to the user.
That gave me ~100MB compared to previous calls.
